name: Arc Raiders Upload

on:
  workflow_dispatch:
  schedule:
    - cron: '0 14 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Decode and save Google client secret
      env:
        GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET_JSON }}
      run: |
        echo "$GOOGLE_CLIENT_SECRET_JSON" | base64 --decode > client_secret.json
    - name: Decode and save YouTube credentials
      env:
        YOUTUBE_CREDENTIALS: ${{ secrets.ARC_RAIDERS_YOUTUBE_CHANNEL_PICKLE }}
      run: |
        echo "$YOUTUBE_CREDENTIALS" | base64 --decode > youtube_credentials.pickle
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: python run
      run: python twitchimporter.py
      env:
        TWITCH_CLIENT_ID: ${{ secrets.TWITCH_CLIENT_ID }}
        TWITCH_CLIENT_SECRET: ${{ secrets.TWITCH_CLIENT_SECRET }}
        GAME_NAME: "ARC Raiders"
        CHANNEL_ID: ${{ secrets.ARC_RAIDERS_CHANNEL_ID }}