name: League of Legends Upload

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 10,22 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Decode and save Google client secret
      env:
        GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET_JSON }}
      run: |
        echo "$GOOGLE_CLIENT_SECRET_JSON" | base64 --decode > client_secret.json
    - name: Decode and save YouTube credentials
      env:
        YOUTUBE_CREDENTIALS: ${{ secrets.LEAGUE_OF_LEGENDS_YOUTUBE_CHANNEL_PICKLE }}
      run: |
        echo "$YOUTUBE_CREDENTIALS" | base64 --decode > youtube_credentials.pickle
    - name: docker build
      run: docker build -t youtubetotwitch .
    - name: python run
      run: |
      docker run -e TWITCH_CLIENT_ID=${{ secrets.TWITCH_CLIENT_ID }} -e TWITCH_CLIENT_SECRET=${{ secrets.TWITCH_CLIENT_SECRET }} -e YOUTUBE_DESCRIPTION=${{ secrets.YOUTUBE_DESCRIPTION }} -e CHANNEL_ID=${{ secrets.LOL_CHANNEL_ID }} -e OUTRO_ID=${{ secrets.YOUTUBE_OUTRO_ID }} youtubetotwitch
      